### ISSUE TITLE
missing link to forum from website, should we drop the forum completely ?

### ISSUE THREAD

**Issue by electronoob** [electronoob/agarmods#105]

**Comment by N0rth3rnL1ghts** [comment]
im kinda down for that i mean not alot of people would even use it

**Comment by Mevin1** [comment]
Missing completely? Its at the bottom on the home page.

**Comment by electronoob** [comment]
yep and the traffic it provides is tremendous, not.

**Comment by electronoob** [comment]
forum server reinstalled with debian and dropped parallels
