### ISSUE TITLE
[Suggestion] Show the available hotkeys on the top middle of the screen instead of being something you have to click on and get in the way of playing.

### ISSUE THREAD

**Issue by asweiler** [electronoob/agarmods#130]
This would be really nice so in case you forget a hotkey you don't have to wait till you die or something in order to go see what the hotkey you forgot was.

**Comment by Mevin1** [comment]
Thank you for the suggestion, but as much as this may be useful, hotkeys are to be remembered, and mostly, we don't want to be adding more clutter to the ui as you play.

**Comment by asweiler** [comment]
Alright, I figured for that kind of person it could be a simple checkbox to enable/disable showing it. Although I guess one more checkbox could be considered as more clutter too.

I guess I could just make my own little script that adds it :)
