### ISSUE TITLE
Hotkeys button does not work.

### ISSUE THREAD

**Issue by asweiler** [electronoob/agarmods#144]
I am sure you already know, but when I click on Hotkeys I get a popup saying NaN. Just wondering if this is intentional and a work in progress or just a bug/typo in the code. Thanks <3 Aaron

**Comment by Mevin1** [comment]
Could have sworn i fixed this several hours ago

**Comment by Mevin1** [comment]
done

**Comment by asweiler** [comment]
Thanks <3 Aaron
