### ISSUE TITLE
Facebook button does not work.

### ISSUE THREAD

**Issue by asweiler** [electronoob/agarmods#146]
Just in case someone wants to use it (for giggles or for the exp to start with higher mass), it might be good to get it working. I can make a video of proof that it does not work for me on Chrome if you would like.

**Comment by Irraquated** [comment]
I would like to see a video @asweiler , it seems to be working for me.

**Comment by asweiler** [comment]
Cancel that it had to be temp bug. The issue I have with it all now is they don't give you a way to logout of the facebook think so now I am perma logged in to it.
