### ISSUE TITLE
Region/Mode vs IP:PORT

### ISSUE THREAD

**Issue by YrOnSai** [electronoob/agarmods#21]
Apropos to the Menu, there continues to be confusion on how the script works with entering the server information and selecting a region with mode type.  We know that each mode is on different servers and so are the regions.  I have a suggestion that may eliminate most of the misunderstandings.

Proposal:
Add two Radio Buttons at the top of the Menu (Region/Mode Selection and Input Server Data)
     The idea is to have it default to Region/Mode Selection, but players will be able to click on the radio button (Input Server Data) to paste the IP and Port of a known realm to match up with friends.
     This also would in theory remove the need to "F5 Harder" if wanting to change game modes or other servers.

**Comment by Mevin1** [comment]
This isn't an issue anynore.
