### ISSUE TITLE
website: some bugs, menu bar when scrolling and general layout

### ISSUE THREAD

**Issue by electronoob** [electronoob/agarmods#69]
![11271200_10155592728765383_549027569_n](https://cloud.githubusercontent.com/assets/8988109/7772902/f1bcca98-0098-11e5-985c-caa6d90e886b.jpg)
![11303437_10155592734140383_17809461_n](https://cloud.githubusercontent.com/assets/8988109/7772905/f4461b2a-0098-11e5-9d94-e1b34ad294ad.jpg)

**Comment by YrOnSai** [comment]
As expected, I only was able to integrate the menu into the new settings given the time.  It may take some time to fix the button and video.

**Comment by electronoob** [comment]
okies bro, understood.

**Comment by YrOnSai** [comment]
Completed!
