### ISSUE TITLE
when viewing site with https instead of just http - site looks messed up

### ISSUE THREAD

**Issue by electronoob** [electronoob/agarmods#85]
https://agariomods.com/

looks horrible when compared to

http://agariomods.com/

**Comment by YrOnSai** [comment]
I should be able to fix this in the morning.

**Comment by YrOnSai** [comment]
Hmm, this is a little harder than I thought.

I have found another problem when fixing this.  I header links are linked to http-only.  I am going to make it so that if you want to use https and clicking links will lead to https aswell.

**Comment by YrOnSai** [comment]
I figured it out.  When pushing the logo linking on the home page earlier I somehow missed editing bootstrap css ref.  This is going to be easy.

**Comment by asweiler** [comment]
This seems to be fixed so why not close this issue? Just wondering :P

**Comment by Irraquated** [comment]
@asweiler We tend to not be very "good"(?) at closing issues :P

**Comment by asweiler** [comment]
Ah ok np :)
