### ISSUE TITLE
Play without Region or Server

### ISSUE THREAD

**Issue by YrOnSai** [electronoob/agarmods#9]
There seems to be an issue not present in the standard game.  When starting out it is possible to press play without selecting a region or entering ip:port.  Doing so will remove the the menu and present a blank grid.

You can still use "esc" to enter the menu and continue playing as normal.

**Comment by electronoob** [comment]
this will likely be the next bug i fix.

**Comment by electronoob** [comment]
resolved, sorry about the delay in the fix uronsai.
